import { useEffect, useRef } from 'react'
const rgb=(hex)=>[1,3,5].map((i)=>parseInt(hex.slice(i,i+2),16))
export default function WebThreads({color1='#5227FF',color2='#FF9FFC',color3='#FFFFFF',speed=.2,threadCount=7,frequency=4.5,spread=.18,taper=1.1,position=.5,fanMode='center',glow=.02,falloff=.6,thickness=1.1,brightness=.6,opacity=1,mirror=true,shimmer=false,grain=true,grainIntensity=.05,mouseInteraction=true,mouseStrength=.3}){
 const canvasRef=useRef(null)
 useEffect(()=>{const canvas=canvasRef.current,ctx=canvas.getContext('2d',{alpha:true}),colors=[color1,color2,color3].map(rgb),pointer={x:.5,y:.5,tx:.5,ty:.5};let width=1,height=1,raf,frame=0,visible=true
  const resize=()=>{const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);width=Math.max(1,rect.width);height=Math.max(1,rect.height);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0)}
  const move=(e)=>{const rect=canvas.getBoundingClientRect();pointer.tx=(e.clientX-rect.left)/rect.width;pointer.ty=(e.clientY-rect.top)/rect.height}
  const line=(index,time,reflected=false)=>{const c=colors[index%colors.length],normalized=threadCount===1?0:index/(threadCount-1)-.5,fan=fanMode==='center'?normalized:Math.abs(normalized),base=height*(position+fan*spread*(reflected?-1:1)),phase=time*speed*.001+index*.72,gradient=ctx.createLinearGradient(0,0,width,0),alpha=opacity*brightness;gradient.addColorStop(0,`rgba(${c},0)`);gradient.addColorStop(falloff*.5,`rgba(${c},${alpha*.76})`);gradient.addColorStop(.52,`rgba(${c},${alpha})`);gradient.addColorStop(1,`rgba(${c},0)`);ctx.beginPath();for(let step=0;step<=90;step++){const p=step/90,x=p*width,envelope=Math.pow(Math.sin(Math.PI*p),taper),wave=Math.sin(p*Math.PI*frequency+phase)*height*spread*.27*envelope,pull=mouseInteraction?Math.exp(-Math.abs(p-pointer.x)*9)*(pointer.y-position)*height*mouseStrength:0,y=base+(reflected?-wave:wave)+pull;step?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle=gradient;ctx.lineWidth=thickness+(shimmer?Math.sin(phase*3)*.25:0);ctx.shadowBlur=Math.max(0,width*glow);ctx.shadowColor=`rgba(${c},${alpha})`;ctx.stroke()}
  const render=(time)=>{raf=requestAnimationFrame(render);if(!visible||document.hidden)return;pointer.x+=(pointer.tx-pointer.x)*.045;pointer.y+=(pointer.ty-pointer.y)*.045;ctx.clearRect(0,0,width,height);ctx.globalCompositeOperation='lighter';for(let i=0;i<threadCount;i++){line(i,time);if(mirror)line(i,time,true)}ctx.shadowBlur=0;ctx.globalCompositeOperation='source-over';if(grain&&frame++%2===0){ctx.fillStyle=`rgba(255,255,255,${grainIntensity*.16})`;for(let i=0;i<80;i++)ctx.fillRect(Math.random()*width,Math.random()*height,1,1)}}
  const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting}),resizer=new ResizeObserver(resize);observer.observe(canvas);resizer.observe(canvas);addEventListener('pointermove',move,{passive:true});resize();raf=requestAnimationFrame(render);return()=>{cancelAnimationFrame(raf);observer.disconnect();resizer.disconnect();removeEventListener('pointermove',move)}
 },[color1,color2,color3,speed,threadCount,frequency,spread,taper,position,fanMode,glow,falloff,thickness,brightness,opacity,mirror,shimmer,grain,grainIntensity,mouseInteraction,mouseStrength])
 return <canvas ref={canvasRef} className="web-threads" aria-hidden="true" />
}
